import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, users } from '@prisma/client';
import * as argon2 from 'argon2';
import { PrismaService } from '../../database/prisma.service';
import { AuthUser } from '../../common/types/auth-user.type';
import { ResourceScopePolicy } from '../../common/policies/resource-scope.policy';
import { CreateUserDto, ResetPasswordDto, UpdateUserDto, UserQueryDto } from './users.dto';

type Db = PrismaService | Prisma.TransactionClient;
const safeUser = { id: true, employee_code: true, full_name: true, email: true, department_id: true, position_id: true, direct_manager_id: true, status: true, last_login_at: true, created_at: true, updated_at: true, deleted_at: true, departments: { select: { id: true, code: true, name: true } }, positions: { select: { id: true, code: true, name: true, level: true } }, users: { select: { id: true, employee_code: true, full_name: true, email: true, status: true } } } as const;

@Injectable()
export class UsersService {
  constructor(private readonly prisma: PrismaService, private readonly scope: ResourceScopePolicy) {}
  private async audit(db: Db, actor: AuthUser, action: string, id: string, oldData: unknown, newData: unknown) { await db.audit_logs.create({ data: { user_id: actor.id, module: 'users', entity_type: 'user', entity_id: id, action, old_data: oldData as Prisma.InputJsonValue, new_data: newData as Prisma.InputJsonValue } }); }
  private whereForScope(actor: AuthUser): Prisma.usersWhereInput {
    if (this.scope.canAccessGlobal(actor)) return {};
    const scopedDepartments = actor.roles.filter(r => r.scopeType === 'DEPARTMENT' && r.scopeId).map(r => r.scopeId!);
    const own = actor.roles.some(r => r.scopeType === 'SELF');
    const clauses: Prisma.usersWhereInput[] = [];
    if (scopedDepartments.length) clauses.push({ department_id: { in: scopedDepartments } });
    if (own) clauses.push({ id: actor.id });
    if (!clauses.length) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền truy cập phạm vi dữ liệu này.' });
    return { OR: clauses };
  }
  private async userInScope(actor: AuthUser, id: string) { const user = await this.prisma.users.findUnique({ where: { id }, select: safeUser }); if (!user || user.deleted_at) throw new NotFoundException('Không tìm thấy người dùng.'); this.scope.assertResourceScope(actor, { ownerId: user.id, departmentId: user.department_id }); return user; }
  private async ensureActiveReferences(db: Db, departmentId: string, positionId: string) { const [department, position] = await Promise.all([db.departments.findUnique({ where: { id: departmentId } }), db.positions.findUnique({ where: { id: positionId } })]); if (!department || department.status !== 'ACTIVE') throw new BadRequestException({ code: 'USER_INVALID_DEPARTMENT', message: 'Đơn vị phải tồn tại và đang hoạt động.' }); if (!position || position.status !== 'ACTIVE') throw new BadRequestException({ code: 'USER_INVALID_POSITION', message: 'Chức danh phải tồn tại và đang hoạt động.' }); }
  private async validateRoleAssignment(db: Db, actor: AuthUser, roleId: string, scopeType: 'GLOBAL' | 'DEPARTMENT' | 'SELF', departmentId: string) {
    const role = await db.roles.findUnique({ where: { id: roleId }, select: { id: true, code: true, status: true, role_permissions: { select: { permissions: { select: { code: true } } } } } });
    if (!role || role.status !== 'ACTIVE') throw new BadRequestException({ code: 'USER_INVALID_ROLE', message: 'Vai trò phải tồn tại và đang hoạt động.' });
    if (!this.scope.canAccessGlobal(actor)) {
      const actorPermissions = new Set(actor.permissions);
      const forbiddenPermissions = role.role_permissions.map(item => item.permissions.code).filter(code => !actorPermissions.has(code));
      if (forbiddenPermissions.length) throw new ForbiddenException({ code: 'USER_ROLE_PERMISSION_ESCALATION', message: 'Không thể gán vai trò có quyền vượt quá quyền của người thực hiện.' });
    }
    if (scopeType === 'GLOBAL' && !this.scope.canAccessGlobal(actor)) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền gán phạm vi toàn hệ thống.' });
    if (scopeType === 'DEPARTMENT' && !this.scope.canAccessDepartment(actor, departmentId)) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền gán phạm vi đơn vị này.' });
    return { role, scopeId: scopeType === 'DEPARTMENT' ? departmentId : null };
  }
  private async validateManager(db: Db, actor: AuthUser, employeeId: string, managerId: string | null | undefined) { if (!managerId) return; if (employeeId === managerId) throw new BadRequestException({ code: 'USER_MANAGER_CYCLE', message: 'Người dùng không thể là quản lý trực tiếp của chính mình.' }); let cursor: string | null = managerId; let selectedManager = true; const seen = new Set<string>(); while (cursor) { if (cursor === employeeId || seen.has(cursor)) throw new BadRequestException({ code: 'USER_MANAGER_CYCLE', message: 'Quan hệ quản lý tạo thành vòng lặp.' }); seen.add(cursor); const manager: { department_id: string; direct_manager_id: string | null; status: string; deleted_at: Date | null } | null = await db.users.findUnique({ where: { id: cursor }, select: { department_id: true, direct_manager_id: true, status: true, deleted_at: true } }); if (!manager || manager.deleted_at || manager.status !== 'ACTIVE') throw new BadRequestException({ code: 'USER_INVALID_MANAGER', message: 'Quản lý trực tiếp phải tồn tại và đang hoạt động.' }); if (selectedManager && !this.scope.canAccessDepartment(actor, manager.department_id)) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền chọn quản lý trực tiếp ngoài phạm vi đơn vị.' }); selectedManager = false; cursor = manager.direct_manager_id; } }
  private async updateManagerHistory(db: Db, actor: AuthUser, employeeId: string, oldManagerId: string | null, managerId: string | null | undefined) { if (oldManagerId === (managerId ?? null)) return; await db.manager_relationships.updateMany({ where: { employee_id: employeeId, is_primary: true, end_date: null }, data: { end_date: new Date() } }); if (managerId) await db.manager_relationships.create({ data: { employee_id: employeeId, manager_id: managerId, start_date: new Date(), is_primary: true } }); await this.audit(db, actor, 'USER_MANAGER_CHANGED', employeeId, { directManagerId: oldManagerId }, { directManagerId: managerId ?? null }); }
  async findAll(actor: AuthUser, q: UserQueryDto) { const scopeWhere = this.whereForScope(actor); if (q.departmentId && !this.scope.canAccessDepartment(actor, q.departmentId)) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền truy cập đơn vị này.' }); const filters: Prisma.usersWhereInput[] = [scopeWhere, { deleted_at: null }]; if (q.departmentId) filters.push({ department_id: q.departmentId }); if (q.positionId) filters.push({ position_id: q.positionId }); if (q.directManagerId) filters.push({ direct_manager_id: q.directManagerId }); if (q.status) filters.push({ status: q.status }); if (q.search) filters.push({ OR: [{ employee_code: { contains: q.search, mode: 'insensitive' } }, { full_name: { contains: q.search, mode: 'insensitive' } }, { email: { contains: q.search, mode: 'insensitive' } }] }); const where: Prisma.usersWhereInput = { AND: filters }; const [items, total] = await this.prisma.$transaction([this.prisma.users.findMany({ where, select: safeUser, orderBy: { [q.sortBy]: q.sortOrder }, skip: (q.page - 1) * q.limit, take: q.limit }), this.prisma.users.count({ where })]); return { items, page: q.page, limit: q.limit, total }; }
  async findOne(actor: AuthUser, id: string) { return this.userInScope(actor, id); }
  async create(actor: AuthUser, dto: CreateUserDto) { if (!this.scope.canAccessGlobal(actor) && !this.scope.canAccessDepartment(actor, dto.departmentId)) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền tạo người dùng trong đơn vị này.' }); const password_hash = await argon2.hash(dto.password); try { return await this.prisma.$transaction(async db => { await this.ensureActiveReferences(db, dto.departmentId, dto.positionId); const assignment = await this.validateRoleAssignment(db, actor, dto.roleId, dto.roleScopeType, dto.departmentId); const id = crypto.randomUUID(); await this.validateManager(db, actor, id, dto.directManagerId); const user = await db.users.create({ data: { id, employee_code: dto.employeeCode.trim(), full_name: dto.fullName.trim(), email: dto.email.trim().toLowerCase(), password_hash, department_id: dto.departmentId, position_id: dto.positionId, direct_manager_id: dto.directManagerId ?? null }, select: safeUser }); await db.user_roles.create({ data: { user_id: user.id, role_id: assignment.role.id, scope_type: dto.roleScopeType, scope_id: assignment.scopeId, assigned_by: actor.id } }); if (dto.directManagerId) await db.manager_relationships.create({ data: { employee_id: user.id, manager_id: dto.directManagerId, start_date: new Date(), is_primary: true } }); await this.audit(db, actor, 'USER_CREATED', user.id, null, { employeeCode: user.employee_code, departmentId: user.department_id, positionId: user.position_id, directManagerId: user.direct_manager_id, roleCode: assignment.role.code, roleScopeType: dto.roleScopeType, roleScopeId: assignment.scopeId }); return user; }); } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Mã nhân viên hoặc email đã tồn tại.'); throw e; } }
  async update(actor: AuthUser, id: string, dto: UpdateUserDto) { const old = await this.userInScope(actor, id); const targetDepartment = dto.departmentId ?? old.department_id; if (!this.scope.canAccessGlobal(actor) && (!this.scope.canAccessDepartment(actor, old.department_id) || !this.scope.canAccessDepartment(actor, targetDepartment))) throw new ForbiddenException({ code: 'AUTH_SCOPE_DENIED', message: 'Bạn không có quyền thay đổi phạm vi đơn vị này.' }); try { return await this.prisma.$transaction(async db => { await this.ensureActiveReferences(db, targetDepartment, dto.positionId ?? old.position_id); await this.validateManager(db, actor, id, dto.directManagerId === undefined ? old.direct_manager_id : dto.directManagerId); const user = await db.users.update({ where: { id }, data: { ...(dto.employeeCode !== undefined ? { employee_code: dto.employeeCode.trim() } : {}), ...(dto.fullName !== undefined ? { full_name: dto.fullName.trim() } : {}), ...(dto.email !== undefined ? { email: dto.email.trim().toLowerCase() } : {}), ...(dto.departmentId !== undefined ? { department_id: dto.departmentId } : {}), ...(dto.positionId !== undefined ? { position_id: dto.positionId } : {}), ...(dto.directManagerId !== undefined ? { direct_manager_id: dto.directManagerId } : {}), updated_at: new Date() }, select: safeUser }); await this.updateManagerHistory(db, actor, id, old.direct_manager_id, dto.directManagerId === undefined ? old.direct_manager_id : dto.directManagerId); await this.audit(db, actor, 'USER_UPDATED', id, { employeeCode: old.employee_code, departmentId: old.department_id, positionId: old.position_id }, { employeeCode: user.employee_code, departmentId: user.department_id, positionId: user.position_id }); return user; }); } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Mã nhân viên hoặc email đã tồn tại.'); throw e; } }
  private async isLastActiveAdmin(id: string) { const targetAdmin = await this.prisma.user_roles.count({ where: { user_id: id, scope_type: 'GLOBAL', roles: { code: 'ADMIN', status: 'ACTIVE' }, OR: [{ expires_at: null }, { expires_at: { gt: new Date() } }] } }); if (!targetAdmin) return false; const activeAdmins = await this.prisma.users.count({ where: { status: 'ACTIVE', deleted_at: null, user_roles_user_roles_user_idTousers: { some: { scope_type: 'GLOBAL', roles: { code: 'ADMIN', status: 'ACTIVE' }, OR: [{ expires_at: null }, { expires_at: { gt: new Date() } }] } } } }); return activeAdmins <= 1; }
  async setStatus(actor: AuthUser, id: string, status: 'ACTIVE'|'INACTIVE'|'LOCKED') { const old = await this.userInScope(actor, id); if (!this.scope.canAccessGlobal(actor) && !this.scope.canAccessDepartment(actor, old.department_id)) throw new ForbiddenException(); if (status !== 'ACTIVE' && await this.isLastActiveAdmin(id)) throw new BadRequestException({ code: 'USER_LAST_ACTIVE_ADMIN', message: 'Không thể khóa hoặc ngừng hoạt động ADMIN cuối cùng.' }); return this.prisma.$transaction(async db => { const user = await db.users.update({ where: { id }, data: { status, updated_at: new Date() }, select: safeUser }); if (status !== 'ACTIVE') await db.auth_refresh_tokens.updateMany({ where: { user_id: id, revoked_at: null }, data: { revoked_at: new Date() } }); await this.audit(db, actor, status === 'LOCKED' ? 'USER_LOCKED' : status === 'ACTIVE' ? 'USER_ACTIVATED' : 'USER_DEACTIVATED', id, { status: old.status }, { status }); return user; }); }
  async resetPassword(actor: AuthUser, id: string, dto: ResetPasswordDto) { const old = await this.userInScope(actor, id); if (!this.scope.canAccessGlobal(actor) && !this.scope.canAccessDepartment(actor, old.department_id)) throw new ForbiddenException(); const password_hash = await argon2.hash(dto.password); await this.prisma.$transaction(async db => { await db.users.update({ where: { id }, data: { password_hash, updated_at: new Date() } }); await db.auth_refresh_tokens.updateMany({ where: { user_id: id, revoked_at: null }, data: { revoked_at: new Date() } }); await this.audit(db, actor, 'USER_PASSWORD_RESET', id, null, { sessionsRevoked: true }); }); return { success: true }; }
}
