import React, { useState } from 'react';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { EmptyState, ErrorState, FormField, TableContainer } from '../../organization/management-ui';
import { employeeBscApi } from '../services/employee-bsc.service';
import { BscItem, BscScoringPreview } from '../types/employee-bsc.types';

const reasonMessage: Record<string, string> = {
  ACTUAL_NOT_PROVIDED: 'Chưa nhập kết quả', TARGET_NOT_PROVIDED: 'Chưa có chỉ tiêu', TARGET_ZERO_NOT_SCORABLE: 'Chỉ tiêu bằng 0 nên chưa thể tính',
  ACTUAL_ZERO_NOT_SCORABLE: 'Kết quả bằng 0 không thể tính cho KPI càng thấp càng tốt', BINARY_ACTUAL_INVALID: 'KPI đạt/không đạt chỉ nhận 1 hoặc 0', CALCULATION_METHOD_UNSUPPORTED: 'Cách tính điểm chưa được hỗ trợ',
};
type Props = { bscId: string; items: BscItem[]; scoring: BscScoringPreview | null; canManage: boolean; canUpdateActual: boolean; isOfficial?: boolean; onChange: () => Promise<void> };

export const BscItemTable: React.FC<Props> = ({ bscId, items, scoring, canManage, canUpdateActual, isOfficial = false, onChange }) => {
  const [error, setError] = useState(''), [savingId, setSavingId] = useState('');
  const run = async (id: string, action: () => Promise<unknown>) => { setError(''); setSavingId(id); try { await action(); await onChange(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể cập nhật KPI.'); } finally { setSavingId(''); } };
  const scoreByItem = new Map(scoring?.items.map(item => [item.itemId, item]) ?? []);
  const scoreLabel = isOfficial ? 'chính thức' : 'dự kiến';
  return <section aria-labelledby="kpi-table-title"><div className="section-heading"><div><h2 id="kpi-table-title">Danh sách KPI</h2><p>{items.length} KPI · Các cột điểm bên dưới là {scoreLabel}.</p></div>{!canManage && !canUpdateActual && <span className="readonly-indicator">Chỉ đọc</span>}</div>
    {error && <ErrorState error={error}/>} {items.length === 0 ? <EmptyState message="BSC chưa có KPI. Hãy thêm mục tiêu đầu tiên ở biểu mẫu bên dưới."/> : <TableContainer label="Bảng giao mục tiêu và đánh giá kết quả BSC"><table className="kpi-table"><thead><tr><th scope="col">STT</th><th scope="col">Mục tiêu chiến lược (KPO)</th><th scope="col">Đo lường hiệu suất (KPI)</th><th scope="col">ĐVT</th><th scope="col">Chỉ tiêu</th><th scope="col">Tỷ trọng</th><th scope="col">Kết quả</th><th scope="col">TM KQTH</th><th scope="col">Hoàn thành {scoreLabel}</th><th scope="col">Điểm trọng số {scoreLabel}</th><th scope="col">Thao tác</th></tr></thead>
      <tbody>{items.map((item, index) => { const score = scoreByItem.get(item.id); const busy = savingId === item.id; return <tr key={item.id}><td>{index + 1}</td><td className="kpi-name">{item.description?.trim() || '—'}</td><td><strong>{item.kpi_code}</strong><br/>{item.kpi_name}</td><td>{item.measurement_unit || '—'}</td><td>{item.target_value ?? item.target_text ?? '—'}</td><td>{item.weight}%</td><td>{item.actual_value ?? item.actual_text ?? '—'}</td><td className="kpi-note">{item.employee_note?.trim() || '—'}</td>
        <td>{score?.roundedAchievementPercentage == null ? '—' : <span title={`Giá trị chưa làm tròn: ${score.rawAchievementPercentage}%`}>{score.roundedAchievementPercentage}%</span>}{score?.reason && <small className="score-note">{reasonMessage[score.reason] ?? 'Chưa thể tính điểm'}</small>}</td>
        <td>{score?.weightedScore == null ? '—' : score.weightedScore.toFixed(4)}</td>
        <td className="row-actions">{canManage && <form aria-label={`Chỉnh sửa KPI ${item.kpi_code}`} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(item.id, () => employeeBscApi.updateItem(bscId, item.id, { description: data.get('description'), kpiName: data.get('kpiName'), measurementUnit: data.get('measurementUnit'), targetValue: Number(data.get('targetValue')), weight: Number(data.get('weight')), calculationMethod: data.get('calculationMethod') })); }}><Input aria-label={`KPO ${item.kpi_code}`} name="description" defaultValue={item.description ?? ''}/><Input aria-label={`Tên KPI ${item.kpi_code}`} name="kpiName" defaultValue={item.kpi_name} required/><Input aria-label={`Đơn vị tính ${item.kpi_code}`} name="measurementUnit" defaultValue={item.measurement_unit ?? ''}/><Input aria-label={`Chỉ tiêu ${item.kpi_code}`} name="targetValue" type="number" step="any" defaultValue={item.target_value ?? ''} required/><Input aria-label={`Trọng số ${item.kpi_code}`} name="weight" type="number" step="0.01" defaultValue={item.weight} required/><select aria-label={`Cách tính ${item.kpi_code}`} name="calculationMethod" defaultValue={item.calculation_method}><option value="ACTUAL_DIV_TARGET">Càng cao càng tốt</option><option value="TARGET_DIV_ACTUAL">Càng thấp càng tốt</option><option value="BINARY">Đạt / không đạt</option></select><Button type="submit" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu KPI'}</Button><Button variant="destructive" type="button" disabled={busy} onClick={() => { if (window.confirm(`Xóa KPI ${item.kpi_code}? Hành động này không thể hoàn tác.`)) void run(item.id, () => employeeBscApi.deleteItem(bscId, item.id)); }}>Xóa</Button></form>}
          {canUpdateActual && <form aria-label={`Cập nhật kết quả ${item.kpi_code}`} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(item.id, () => employeeBscApi.updateActual(bscId, item.id, { actualValue: Number(data.get('actualValue')), employeeNote: String(data.get('employeeNote') ?? '') })); }}><input aria-label={`Kết quả ${item.kpi_code}`} name="actualValue" type="number" step={item.calculation_method === 'BINARY' ? '1' : 'any'} min={item.calculation_method === 'BINARY' ? '0' : undefined} max={item.calculation_method === 'BINARY' ? '1' : undefined} defaultValue={item.actual_value ?? ''} required/>{item.calculation_method === 'BINARY' && <small>1 = đạt, 0 = không đạt</small>}<input aria-label={`TM KQTH ${item.kpi_code}`} name="employeeNote" placeholder="Thuyết minh kết quả" defaultValue={item.employee_note ?? ''}/><Button type="submit" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu kết quả'}</Button></form>}{!canManage && !canUpdateActual && <span className="readonly-indicator">Đã khóa</span>}</td></tr>; })}</tbody></table></TableContainer>}
    {canManage && <form className="kpi-create-form" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void run('new', async () => { await employeeBscApi.createItem(bscId, { kpiCode: data.get('kpiCode'), description: data.get('description'), kpiName: data.get('kpiName'), measurementUnit: data.get('measurementUnit'), targetValue: Number(data.get('targetValue')), weight: Number(data.get('weight')), calculationMethod: data.get('calculationMethod'), sortOrder: items.length }); form.reset(); }); }}><h3>Thêm mục tiêu BSC</h3><p>Nhập KPO và KPI theo bảng giao mục tiêu. Tổng tỷ trọng của toàn bộ KPI phải bằng 100% trước khi gửi duyệt.</p><div className="form-grid"><FormField label="Mã KPI"><Input name="kpiCode" placeholder="Ví dụ: KPI-01" required/></FormField><FormField label="Mục tiêu chiến lược (KPO)"><Input name="description" placeholder="Mục tiêu cần đạt" required/></FormField><FormField label="Đo lường hiệu suất (KPI)"><Input name="kpiName" placeholder="Nội dung đo lường" required/></FormField><FormField label="Đơn vị tính"><Input name="measurementUnit" placeholder="%, hồ sơ, ngày…"/></FormField><FormField label="Chỉ tiêu"><Input name="targetValue" placeholder="Chỉ tiêu" type="number" step="any" required/></FormField><FormField label="Tỷ trọng (%)"><Input name="weight" placeholder="Tỷ trọng" type="number" step="0.01" required/></FormField><FormField label="Cách tính"><select name="calculationMethod" defaultValue="ACTUAL_DIV_TARGET"><option value="ACTUAL_DIV_TARGET">Càng cao càng tốt</option><option value="TARGET_DIV_ACTUAL">Càng thấp càng tốt</option><option value="BINARY">Đạt / không đạt</option></select></FormField></div><Button type="submit" disabled={savingId === 'new'}>{savingId === 'new' ? 'Đang thêm…' : 'Thêm KPI vào BSC'}</Button></form>}
  </section>;
};
