import { httpClient } from '../../lib/http-client';
export type Page<T> = { items: T[]; page: number; limit: number; total: number };
export type Department = { id: string; code: string; name: string; parent_id: string | null; status: string; departments?: { name: string } | null };
export type Position = { id: string; code: string; name: string; level: number; status: string };
export type User = { id: string; employee_code: string; username: string; full_name: string; email: string; department_id: string; position_id: string; direct_manager_id: string | null; status: string; departments?: { name: string }; positions?: { name: string }; users?: { full_name: string } | null };
export type DepartmentManagerAssignment = { id: string; department_id: string; manager_id: string; start_date: string; end_date: string | null; manager: Pick<User, 'id' | 'employee_code' | 'full_name' | 'email' | 'status'> };
const query = (input: Record<string, string | number | undefined>) => `?${new URLSearchParams(Object.entries(input).filter(([,v]) => v !== undefined && v !== '').map(([k,v]) => [k, String(v)])).toString()}`;
export const organizationApi = {
 departments: (q: Record<string, string | number | undefined>) => httpClient.get<Page<Department>>(`/departments${query(q)}`), department: (id:string) => httpClient.get<Department>(`/departments/${id}`), departmentTree: () => httpClient.get<Department[]>('/departments/tree'), createDepartment: (d: unknown) => httpClient.post<Department>('/departments', d), updateDepartment: (id: string,d: unknown) => httpClient.patch<Department>(`/departments/${id}`,d), departmentStatus: (id:string, active:boolean) => httpClient.post<Department>(`/departments/${id}/${active?'activate':'deactivate'}`),
 departmentManager: (id: string) => httpClient.get<DepartmentManagerAssignment | null>(`/departments/${id}/manager-assignment`), setDepartmentManager: (id: string, managerId: string, reason: string) => httpClient.post<DepartmentManagerAssignment>(`/departments/${id}/manager-assignment`, { managerId, reason }),
 positions: (q: Record<string, string | number | undefined>) => httpClient.get<Page<Position>>(`/positions${query(q)}`), position: (id:string) => httpClient.get<Position>(`/positions/${id}`), createPosition:(d:unknown)=>httpClient.post<Position>('/positions',d), updatePosition:(id:string,d:unknown)=>httpClient.patch<Position>(`/positions/${id}`,d), positionStatus:(id:string,active:boolean)=>httpClient.post<Position>(`/positions/${id}/${active?'activate':'deactivate'}`),
 users: (q: Record<string, string | number | undefined>) => httpClient.get<Page<User>>(`/users${query(q)}`), user:(id:string)=>httpClient.get<User>(`/users/${id}`), createUser:(d:unknown)=>httpClient.post<User>('/users',d), updateUser:(id:string,d:unknown)=>httpClient.patch<User>(`/users/${id}`,d), userStatus:(id:string, action:'activate'|'deactivate'|'lock'|'unlock')=>httpClient.post<User>(`/users/${id}/${action}`), resetPassword:(id:string,password:string)=>httpClient.post(`/users/${id}/reset-password`,{password}),
};
