export enum BscStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RETURNED = 'RETURNED',
  RESUBMITTED = 'RESUBMITTED',
  APPROVED = 'APPROVED',
  UNLOCK_REQUESTED = 'UNLOCK_REQUESTED',
  UNLOCKED = 'UNLOCKED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED'
}

export enum ScopeType {
  GLOBAL = 'GLOBAL',
  DEPARTMENT = 'DEPARTMENT',
  SELF = 'SELF'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}
