export const NOTIFICATION_EVENT = {
  EMPLOYEE_BSC_PLAN_SUBMITTED: 'EMPLOYEE_BSC_PLAN_SUBMITTED',
  EMPLOYEE_BSC_PLAN_APPROVED: 'EMPLOYEE_BSC_PLAN_APPROVED',
  EMPLOYEE_BSC_PLAN_RETURNED: 'EMPLOYEE_BSC_PLAN_RETURNED',
  EMPLOYEE_BSC_EVALUATION_SUBMITTED: 'EMPLOYEE_BSC_EVALUATION_SUBMITTED',
  EMPLOYEE_BSC_EVALUATION_APPROVED: 'EMPLOYEE_BSC_EVALUATION_APPROVED',
  EMPLOYEE_BSC_EVALUATION_RETURNED: 'EMPLOYEE_BSC_EVALUATION_RETURNED',
  EMPLOYEE_BSC_REOPEN_REQUESTED: 'EMPLOYEE_BSC_REOPEN_REQUESTED',
  EMPLOYEE_BSC_REOPEN_APPROVED: 'EMPLOYEE_BSC_REOPEN_APPROVED',
  EMPLOYEE_BSC_REOPEN_REJECTED: 'EMPLOYEE_BSC_REOPEN_REJECTED',
  DEPARTMENT_BSC_PLAN_SUBMITTED: 'DEPARTMENT_BSC_PLAN_SUBMITTED',
  DEPARTMENT_BSC_PLAN_APPROVED: 'DEPARTMENT_BSC_PLAN_APPROVED',
  DEPARTMENT_BSC_PLAN_RETURNED: 'DEPARTMENT_BSC_PLAN_RETURNED',
  DEPARTMENT_BSC_EVALUATION_SUBMITTED: 'DEPARTMENT_BSC_EVALUATION_SUBMITTED',
  DEPARTMENT_BSC_EVALUATION_APPROVED: 'DEPARTMENT_BSC_EVALUATION_APPROVED',
  DEPARTMENT_BSC_EVALUATION_RETURNED: 'DEPARTMENT_BSC_EVALUATION_RETURNED',
  DEPARTMENT_BSC_REOPEN_REQUESTED: 'DEPARTMENT_BSC_REOPEN_REQUESTED',
  DEPARTMENT_BSC_REOPEN_APPROVED: 'DEPARTMENT_BSC_REOPEN_APPROVED',
  DEPARTMENT_BSC_REOPEN_REJECTED: 'DEPARTMENT_BSC_REOPEN_REJECTED',
} as const;

export type NotificationEventType = typeof NOTIFICATION_EVENT[keyof typeof NOTIFICATION_EVENT];

export interface NotificationEvent {
  type: NotificationEventType;
  resourceId: string;
  sourceId: string;
  actorId: string;
}

export type NotificationStage = 'PLAN' | 'EVALUATION';

