import React, { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { PermissionGate } from '../../auth/components/permission-gate';
import { Department, organizationApi } from '../organization-api';
import { ConfirmButton, EmptyState, ErrorState, FormField, LoadingState, PageHeader, Pagination, SearchInput, StatusBadge } from '../management-ui';

export const DepartmentsPage: React.FC = () => {
  const [items, setItems] = useState<Department[]>([]), [tree, setTree] = useState<Department[]>([]);
  const [search, setSearch] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const [form, setForm] = useState({ code: '', name: '', parentId: '' });
  const load = useCallback(() => { setLoading(true); setError(''); Promise.all([organizationApi.departments({ search, status, page, limit: 20 }), organizationApi.departmentTree()]).then(([result, nodes]) => { setItems(result.items); setTotal(result.total); setTree(nodes); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [search, status, page]);
  useEffect(() => { load(); }, [load]);
  const create = async () => { if (!form.code.trim() || !form.name.trim()) return setError('Mã và tên là bắt buộc.'); try { await organizationApi.createDepartment({ code: form.code.toUpperCase(), name: form.name, parentId: form.parentId || null }); setForm({ code: '', name: '', parentId: '' }); setSuccess('Đã tạo đơn vị.'); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo đơn vị.'); } };
  return <main><PageHeader title="Đơn vị" /><PermissionGate permission="department.manage"><section><FormField label="Mã"><input value={form.code} onChange={e => setForm({ ...form, code: e.target.value.toUpperCase() })} /></FormField><FormField label="Tên"><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></FormField><FormField label="Đơn vị cha"><select value={form.parentId} onChange={e => setForm({ ...form, parentId: e.target.value })}><option value="">Không có</option>{tree.filter(x => x.status === 'ACTIVE').map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><button onClick={() => void create()}>Tạo đơn vị</button></section></PermissionGate>{success && <p role="status">{success}</p>}<SearchInput value={search} onChange={value => { setSearch(value); setPage(1); }} /><select aria-label="Trạng thái" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="INACTIVE">Ngừng hoạt động</option></select>{loading ? <LoadingState /> : error ? <ErrorState error={error} /> : items.length === 0 ? <EmptyState /> : <table><thead><tr><th>Mã</th><th>Tên</th><th>Đơn vị cha</th><th>Trạng thái</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.departments?.name ?? '—'}</td><td><StatusBadge status={item.status} /></td><td><PermissionGate permission="department.manage"><Link to={`/management/departments/${item.id}/edit`}>Sửa</Link> <ConfirmButton message="Xác nhận thay đổi trạng thái?" onConfirm={() => void organizationApi.departmentStatus(item.id, item.status !== 'ACTIVE').then(load).catch(e => setError(e.message))}>{item.status === 'ACTIVE' ? 'Ngừng' : 'Kích hoạt'}</ConfirmButton></PermissionGate></td></tr>)}</tbody></table>}<Pagination page={page} total={total} limit={20} onChange={setPage} /></main>;
};
