import React, { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { PermissionGate } from '../../auth/components/permission-gate';
import { organizationApi, Position } from '../organization-api';
import { ConfirmButton, EmptyState, ErrorState, FormField, LoadingState, PageHeader, Pagination, SearchInput, StatusBadge } from '../management-ui';
export const PositionsPage: React.FC = () => {
  const [items, setItems] = useState<Position[]>([]), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const [form, setForm] = useState({ code: '', name: '', level: '1' });
  const load = useCallback(() => { setLoading(true); setError(''); organizationApi.positions({ search, status, page, limit: 20 }).then(result => { setItems(result.items); setTotal(result.total); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [search, status, page]);
  useEffect(() => { load(); }, [load]);
  const create = async () => { const level = Number(form.level); if (!form.code.trim() || !form.name.trim() || !Number.isInteger(level) || level <= 0) return setError('Mã, tên và cấp bậc nguyên dương là bắt buộc.'); try { await organizationApi.createPosition({ code: form.code.toUpperCase(), name: form.name, level }); setForm({ code: '', name: '', level: '1' }); setSuccess('Đã tạo chức danh.'); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo chức danh.'); } };
  return <main><PageHeader title="Chức danh" /><PermissionGate permission="position.manage"><section><FormField label="Mã"><input value={form.code} onChange={e => setForm({ ...form, code: e.target.value.toUpperCase() })} /></FormField><FormField label="Tên"><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></FormField><FormField label="Cấp bậc"><input type="number" min="1" value={form.level} onChange={e => setForm({ ...form, level: e.target.value })} /></FormField><button onClick={() => void create()}>Tạo chức danh</button></section></PermissionGate>{success && <p role="status">{success}</p>}<SearchInput value={search} onChange={value => { setSearch(value); setPage(1); }} /><select aria-label="Trạng thái" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="INACTIVE">Ngừng hoạt động</option></select>{loading ? <LoadingState /> : error ? <ErrorState error={error} /> : items.length === 0 ? <EmptyState /> : <table><thead><tr><th>Mã</th><th>Tên</th><th>Cấp</th><th>Trạng thái</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.level}</td><td><StatusBadge status={item.status} /></td><td><PermissionGate permission="position.manage"><Link to={`/management/positions/${item.id}/edit`}>Sửa</Link> <ConfirmButton message="Xác nhận thay đổi trạng thái?" onConfirm={() => void organizationApi.positionStatus(item.id, item.status !== 'ACTIVE').then(load).catch(e => setError(e.message))}>{item.status === 'ACTIVE' ? 'Ngừng' : 'Kích hoạt'}</ConfirmButton></PermissionGate></td></tr>)}</tbody></table>}<Pagination page={page} total={total} limit={20} onChange={setPage} /></main>;
};
