import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, positions } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { AuthUser } from '../../common/types/auth-user.type';
import { ResourceScopePolicy } from '../../common/policies/resource-scope.policy';
import { PositionMutationDto, PositionQueryDto, UpdatePositionDto } from './positions.dto';
@Injectable()
export class PositionsService {
  constructor(private readonly prisma: PrismaService, private readonly scope: ResourceScopePolicy) {}
  private global(actor: AuthUser) { this.scope.assertResourceScope(actor, {}); }
  private async audit(actor: AuthUser, action: string, id: string, oldData: unknown, newData: unknown) { await this.prisma.audit_logs.create({ data: { user_id: actor.id, module: 'organization', entity_type: 'position', entity_id: id, action, old_data: oldData as Prisma.InputJsonValue, new_data: newData as Prisma.InputJsonValue } }); }
  async findAll(actor: AuthUser, q: PositionQueryDto) { this.global(actor); const legacyCandidates = await this.prisma.positions.findMany({ where: { code: { contains: 'ADMIN', mode: 'insensitive' } }, select: { id: true, code: true } }); const legacyAdminIds = legacyCandidates.filter(item => item.code.trim().toUpperCase() === 'ADMIN').map(item => item.id); const where: Prisma.positionsWhereInput = { ...(legacyAdminIds.length ? { id: { notIn: legacyAdminIds } } : {}), ...(q.status ? { status: q.status } : {}), ...(q.search ? { OR: [{ code: { contains: q.search, mode: 'insensitive' } }, { name: { contains: q.search, mode: 'insensitive' } }] } : {}) }; const orderBy: Prisma.positionsOrderByWithRelationInput[] = q.sortBy === 'level' ? [{ level: q.sortOrder }, { name: 'asc' }] : [{ [q.sortBy]: q.sortOrder }]; const [items, total] = await this.prisma.$transaction([this.prisma.positions.findMany({ where, include: { _count: { select: { users: true } } }, orderBy, skip: (q.page - 1) * q.limit, take: q.limit }), this.prisma.positions.count({ where })]); return { items, page: q.page, limit: q.limit, total }; }
  async findOne(actor: AuthUser, id: string): Promise<positions> { this.global(actor); const item = await this.prisma.positions.findUnique({ where: { id } }); if (!item) throw new NotFoundException('Không tìm thấy chức danh.'); return item; }
  async create(actor: AuthUser, dto: PositionMutationDto) { this.global(actor); try { const item = await this.prisma.positions.create({ data: { code: dto.code.trim().toUpperCase(), name: dto.name.trim(), level: dto.level } }); await this.audit(actor, 'POSITION_CREATED', item.id, null, { code: item.code, name: item.name, level: item.level }); return item; } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException({ code: 'POSITION_CODE_EXISTS', message: 'Mã chức danh đã tồn tại.' }); throw e; } }
  async update(actor: AuthUser, id: string, dto: UpdatePositionDto) { this.global(actor); const old = await this.findOne(actor, id); try { const item = await this.prisma.positions.update({ where: { id }, data: { ...(dto.code !== undefined ? { code: dto.code.trim().toUpperCase() } : {}), ...(dto.name !== undefined ? { name: dto.name.trim() } : {}), ...(dto.level !== undefined ? { level: dto.level } : {}), updated_at: new Date() } }); await this.audit(actor, 'POSITION_UPDATED', id, { code: old.code, name: old.name, level: old.level }, { code: item.code, name: item.name, level: item.level }); return item; } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException({ code: 'POSITION_CODE_EXISTS', message: 'Mã chức danh đã tồn tại.' }); throw e; } }
  async setStatus(actor: AuthUser, id: string, status: 'ACTIVE' | 'INACTIVE') { this.global(actor); const old = await this.findOne(actor, id); if (status === 'INACTIVE') { const activeUsers = await this.prisma.users.count({ where: { position_id: id, status: 'ACTIVE', deleted_at: null } }); if (activeUsers) throw new BadRequestException({ code: 'POSITION_HAS_ACTIVE_USERS', message: 'Không thể ngừng hoạt động chức danh còn người dùng đang hoạt động.' }); } const item = await this.prisma.positions.update({ where: { id }, data: { status, updated_at: new Date() } }); await this.audit(actor, status === 'ACTIVE' ? 'POSITION_ACTIVATED' : 'POSITION_DEACTIVATED', id, { status: old.status }, { status }); return item; }
}
